insert into currency(code, name, symbol, exp, flag) VALUES
  ('AED', 'Emirati Dirham', '.د.ب', 2, 'ae' ),
  ('AFN', 'Afghan Afghani', '؋', 2, 'af' ),
  ('ALL', 'Albanian lek', 'lek', 2, 'al' ),
  ('AMD', 'Armenian dram', 'AMD', 2, 'am' ),
  ('ANG', 'Dutch Guilder', 'ƒ', 2, 'an' ),
  ('AOA', 'Angolan Kwanza', 'Kz', 2, 'ao' ),
  ('ARS', 'Argentine peso', '$', 2, 'ar' ),
  ('AUD', 'Australian Dollar', '$', 2, 'au' ),
  ('AWG', 'Arubin florin', 'ƒ', 2, 'aw' ),
  ('AZN', 'Azerbaijani manat', 'ман', 2, 'az' ),
  ('BAM', 'Bosnian Convertible Marka', 'KM', 2, 'ba' ),
  ('BBD', 'Barbadian dollar', '$', 2, 'bb' ),
  ('BDT', 'Bangladeshi Taka', 'Tk', 2, 'bd' ),
  ('BGN', 'Bulgarian lev', 'лв', 2, 'bg' ),
  ('BHD', 'Bahraini Dinar', '.د.ب or BD', 3, 'bh' ),
  ('BIF', 'Burundian Franc', 'FBu', 0, 'bi' ),
  ('BMD', 'Bermudian dollar', '$', 2, 'bm' ),
  ('BND', 'Bruneian Dollar', '$', 2, 'bn' ),
  ('BOB', 'Bolivian Boliviano', '$b', 2, 'bo' ),
  ('BRL', 'Brazilian real', 'R$', 2, 'br' ),
  ('BSD', 'Bahamian dollar', 'B$', 2, 'bs' ),
  ('BTN', 'Bhutanese Ngultrum', 'Nu.', 2, 'bt' ),
  ('BWP', 'Botswana Pula', 'P', 2, 'bw' ),
  ('BYR', 'Belarusian ruble', 'р', 2, 'by' ),
  ('BZD', 'Belize dollar', 'BZ$', 2, 'bz' ),
  ('CAD', 'Canadian Dollar', '$', 2, 'ca' ),
  ('CHF', 'Swiss Franc', 'CHF', 2, 'ch' ),
  ('CLP', 'Chilean Peso', '$', 0, 'cl' ),
  ('CNY', 'Yuan or chinese renminbi', '¥', 2, 'cn' ),
  ('COP', 'Colombian peso', '$', 2, 'co' ),
  ('CRC', 'Costa Rican colón', '₡', 2, 'cr' ),
  ('CUC', 'Cuban convertible peso', '$', 2, 'cu' ),
  ('CUP', 'Cuban peso', '₱', 2, 'cu' ),
  ('CVE', 'Cape Verdean Escudo', '$', 0, 'cv' ),
  ('CZK', 'Czech koruna', 'Kč', 2, 'cz' ),
  ('DJF', 'Djiboutian Franc', 'fdj', 0, 'dj' ),
  ('DKK', 'Danish krone', 'kr', 2, 'dk' ),
  ('DOP', 'Dominican peso', '$', 2, 'do' ),
  ('DZD', 'Algerian Dinar', 'جد', 2, 'dz' ),
  ('EGP', 'Egyptian Pound', '£ ', 2, 'eg' ),
  ('ERN', 'Eritrean nakfa', 'ናቕፋ', 2, 'er' ),
  ('ETB', 'Ethiopian Birr', 'Br', 2, 'et' ),
  ('EUR', 'Euro', '€', 2, 'eu' ),
  ('FJD', 'Fijian dollar', '$', 2, 'fj' ),
  ('FKP', 'Falkland Island Pound', '£', 2, 'fk' ),
  ('GBP', 'British Pound', '£', 2, 'gb' ),
  ('GEL', 'Georgian lari', 'ლ', 2, 'ge' ),
  ('GHS', 'Ghanaian Cedi', 'GH¢', 2, 'gh' ),
  ('GIP', 'Gibraltar pound', '£', 2, 'gi' ),
  ('GMD', 'Gambian dalasi', 'D', 2, 'gm' ),
  ('GNF', 'Guinean Franc', 'GNF', 0, 'gn' ),
  ('GTQ', 'Guatemalan Quetzal', 'Q', 2, 'gt' ),
  ('GYD', 'Guyanese dollar', '$', 2, 'gy' ),
  ('HKD', 'Hong Kong dollar', 'HK$', 2, 'hk' ),
  ('HNL', 'Honduran lempira', 'L', 2, 'hn' ),
  ('HRK', 'Croatian kuna', 'kn', 2, 'hr' ),
  ('HTG', 'Haitian gourde', 'G', 2, 'ht' ),
  ('HUF', 'Hungarian forint', 'Ft', 2, 'hu' ),
  ('IDR', 'Indonesian Rupiah', 'Rp', 2, 'id' ),
  ('ILS', 'Israeli Shekel', '₪', 2, 'il' ),
  ('INR', 'Indian Rupee', '₹', 2, 'in' ),
  ('IQD', 'Iraqi Dinar', 'ع.د', 3, 'iq' ),
  ('IRR', 'Iranian Rial', '﷼', 2, 'ir' ),
  ('ISK', 'Icelandic Krona', 'kr', 0, 'is' ),
  ('JMD', 'Jamaican dollar', 'J$', 2, 'jm' ),
  ('JOD', 'Jordanian Dinar', 'JOD', 3, 'jo' ),
  ('JPY', 'Japanese yen', '¥', 0, 'jp' ),
  ('KES', 'Kenyan Shilling', 'KSh', 2, 'ke' ),
  ('KGS', 'Kyrgyzstani som', 'лв', 2, 'kg' ),
  ('KHR', 'Cambodian Riel', '៛', 2, 'kh' ),
  ('KMF', 'Comoro Franc', 'KMF', 0, 'km' ),
  ('KPW', 'North Korean won', '₩', 2, 'kp' ),
  ('KRW', 'South Korean won', '₩', 0, 'kr' ),
  ('KWD', 'Kuwaiti Dinar', 'ك', 3, 'kw' ),
  ('KYD', 'Caymanian Dollar', '$', 2, 'ky' ),
  ('KZT', 'Kazakhstani tenge', '₸', 2, 'kz' ),
  ('LAK', 'Lao or Laotian Kip', '₭', 2, 'la' ),
  ('LBP', 'Lebanese Pound', 'ل.ل', 2, 'lb' ),
  ('LKR', 'Sri Lankan Rupee', 'Rs', 2, 'lk' ),
  ('LRD', 'Liberian Dollar', '$', 2, 'lr' ),
  ('LSL', 'Lesotho loti', 'L or M', 2, 'ls' ),
  ('LTL', 'Lithuanian litas', 'Lt', 2, 'lt' ),
  ('LYD', 'Libyan Dinar', ' د.ل', 3, 'ly' ),
  ('MAD', 'Moroccan Dirham', 'م.د.', 2, 'ma' ),
  ('MDL', 'Moldovan Leu', 'L', 2, 'md' ),
  ('MGA', 'Malagasy Ariary', 'Ar', 2, 'mg' ),
  ('MKD', 'Macedonian Denar', 'ден', 2, 'mk' ),
  ('MMK', 'Burmese Kyat', 'K', 2, 'mm' ),
  ('MNT', 'Mongolian Tughrik', '₮', 2, 'mn' ),
  ('MOP', 'Macau Pataca', 'MOP$', 2, 'mo' ),
  ('MRO', 'Mauritanian Ouguiya', 'UM', 2, 'mr' ),
  ('MUR', 'Mauritian rupee', 'Rs', 2, 'mu' ),
  ('MVR', 'Maldivian Rufiyaa', 'rf', 2, 'mv' ),
  ('MWK', 'Malawian Kwacha', 'MK', 2, 'mw' ),
  ('MXN', 'Mexico Peso', '$', 2, 'mx' ),
  ('MYR', 'Malaysian Ringgit', 'RM', 2, 'my' ),
  ('MZN', 'Mozambican Metical', 'MT', 2, 'mz' ),
  ('NAD', 'Namibian Dollar', '$', 2, 'na' ),
  ('NGN', 'Nigerian Naira', '₦', 2, 'ng' ),
  ('NIO', 'Nicaraguan córdoba', 'C$', 2, 'ni' ),
  ('NOK', 'Norwegian krone', 'kr', 2, 'no' ),
  ('NPR', 'Nepalese Rupee', 'Rs', 2, 'np' ),
  ('NZD', 'New Zealand Dollar', '$', 2, 'nz' ),
  ('OMR', 'Omani Rial', 'ع.ر.', 3, 'om' ),
  ('PAB', 'Balboa panamérn', 'B/', 2, 'pa' ),
  ('PEN', 'Peruvian nuevo sol', 'S/', 2, 'pe' ),
  ('PGK', 'Papua New Guinean Kina', 'K', 2, 'pg' ),
  ('PHP', 'Philippine Peso', '₱', 2, 'ph' ),
  ('PKR', 'Pakistani Rupee', 'Rs', 2, 'pk' ),
  ('PLN', 'Polish złoty', 'zł', 2, 'pl' ),
  ('PYG', 'Paraguayan guarani', '₲', 0, 'py' ),
  ('QAR', 'Qatari Riyal', 'ق.ر ', 2, 'qa' ),
  ('RON', 'Romanian leu', 'lei', 2, 'ro' ),
  ('RSD', 'Serbian Dinar', 'РСД', 2, 'rs' ),
  ('RUB', 'Russian Rouble', '₽', 2, 'ru' ),
  ('RWF', 'Rwandan franc', 'FRw, RF, R₣', 0, 'rw' ),
  ('SAR', 'Saudi Arabian Riyal', 'ر.س', 2, 'sa' ),
  ('SBD', 'Solomon Islander Dollar', 'SI$', 2, 'sb' ),
  ('SCR', 'Seychellois Rupee', 'Rs', 2, 'sc' ),
  ('SDG', 'Sudanese Pound', 'SDG', 2, 'sd' ),
  ('SEK', 'Swedish krona', 'kr', 2, 'se' ),
  ('SGD', 'Singapore Dollar', '$', 2, 'sg' ),
  ('SLL', 'Sierra Leonean Leone', 'Le', 2, 'sl' ),
  ('SOS', 'Somali Shilling', 'S', 2, 'so' ),
  ('SRD', 'Surinamese dollar', '$', 2, 'sr' ),
  ('SYP', 'Syrian Pound', '£', 2, 'sy' ),
  ('SZL', 'Swazi Lilangeni', 'L or E', 2, 'sz' ),
  ('THB', 'Thai Baht', '฿', 2, 'th' ),
  ('TJS', 'Tajikistani somoni', 'TJS', 2, 'tj' ),
  ('TMT', 'Turkmenistan manat', 'T', 2, 'tm' ),
  ('TND', 'Tunisian Dinar', 'TND', 3, 'tn' ),
  ('TOP', 'Tongan Pa anga', 'T$', 2, 'to' ),
  ('TRY', 'Turkish Lira', '₺', 2, 'tr' ),
  ('TTD', 'Trinidadian dollar', 'TT$', 2, 'tt' ),
  ('TWD', 'Taiwan New Dollar', 'NT$', 2, 'tw' ),
  ('TZS', 'Tanzanian Shilling', 'Sh', 2, 'tz' ),
  ('UAH', 'Ukrainian Hryvnia', '₴', 2, 'ua' ),
  ('UGX', 'Ugandan Shilling', 'USh', 0, 'ug' ),
  ('USD', 'US Dollar', '$', 2, 'us' ),
  ('UYU', 'Uruguayan peso', '$U', 2, 'uy' ),
  ('UZS', 'Uzbekistani som', 'лв', 2, 'uz' ),
  ('VEF', 'Venezuelan bolivar', 'Bs', 2, 've' ),
  ('VND', 'Vietnamese Dong', '₫', 0, 'vn' ),
  ('VUV', 'Vanuatu Vatu', 'VT', 0, 'vu' ),
  ('WST', 'Samoan Tālā', '$', 2, 'ws' ),
  ('YER', 'Yemeni Rial', 'YER', 2, 'ye' ),
  ('ZAR', 'South African Rand', 'R', 2, 'za' ),
  ('ZMW', 'Zambian Kwacha', 'ZMK', 2, 'zm' ),
  ('ZWD', 'Zimbabwean Dollar', 'Z$', 2, 'zw' ),
  ('XAU', 'Gold, troy ounce', 'XAU', 2, '' );